title: Dererif
email: ""
description: Notes on architecture, debugging, and game development from Dererif.
baseurl: ""
url: "https://parkbrother86.github.io"
lang: en-US
timezone: Asia/Seoul
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
remote_theme: pages-themes/dinky@v0.2.0
show_downloads: false
google_analytics: G-01GER2QJG9
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
author:
  name: Dererif
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: default
