title: geyopa blog
email: ""
description: Notes, posts, and updates from geyopa.
baseurl: ""
url: "https://parkbrother86.github.io"
lang: en
timezone: Asia/Seoul
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
plugins: []
google_analytics_id: "G-01GER2QJG9"
